[Information]
Name=Classic icon set
Author=The DFendX Team

; DFendX will use the buildin default icon for each icon not defined
; here. Because there are no icon definitions in this file DFendX will
; use the buildin icons if this icon set is activated.