unit HelpContextMap;
{ Auto-generated from Help\English\English.hhp [MAP] by BuildHelp.ps1; do not hand-edit. }
interface

function HelpContextToTopic(const ContextID: Integer): string;

implementation

function HelpContextToTopic(const ContextID: Integer): string;
begin
  Result := '';
  case ContextID of
    1 : Result := 'Index.html';
    2 : Result := 'Introduction.html';
    3 : Result := 'FAQ.html';
    4 : Result := 'FirstRunWizard.html';
    5 : Result := 'Introduction2.html';
    { Menu.html only meta-refreshes to Index#Menu; open Index.html at top (Welcome). }
    6 : Result := 'Index.html';
    7 : Result := 'WhatsNew.html';
 1001 : Result := 'FileExportConf.html';
 1002 : Result := 'FileExportProf.html';
 1003 : Result := 'FileExportList.html';
 1011 : Result := 'FileImportZip.html';
 1012 : Result := 'FileExportBuildInstallers.html';
 1013 : Result := 'FileExportBuildZipPackages.html';
 1014 : Result := 'FileImportPackage.html';
 1015 : Result := 'FileExportPackageList.html';
 1100 : Result := 'FileOptions.html';
 1101 : Result := 'FileOptionsGeneral.html';
 1102 : Result := 'FileOptionsDirectories.html';
 1103 : Result := 'FileOptionsSecurity.html';
 1104 : Result := 'FileOptionsCompressionSettings.html';
 1105 : Result := 'FileOptionsWineSupport.html';
 1106 : Result := 'FileOptionsUserInterface.html';
 1107 : Result := 'FileOptionsLanguage.html';
 1108 : Result := 'FileOptionsToolbar.html';
 1109 : Result := 'FileOptionsColumnsInTheGamesList.html';
 1110 : Result := 'FileOptionsAppearanceList.html';
 1111 : Result := 'FileOptionsListInScreenshotMode.html';
 1112 : Result := 'FileOptionsAppearanceTree.html';
 1113 : Result := 'FileOptionsAppearanceScreenshots.html';
 1114 : Result := 'FileOptionsProfileEditor.html';
 1115 : Result := 'FileOptionsDefaultValues.html';
 1116 : Result := 'FileOptionsDOSBox.html';
 1117 : Result := 'FileOptionsDOSBoxCVSFeatures.html';
 1118 : Result := 'FileOptionsFreeDOS.html';
 1119 : Result := 'FileOptionsScummVM.html';
 1120 : Result := 'FileOptionsQBasic.html';
 1121 : Result := 'FileOptionsWaveEncoder.html';
 1122 : Result := 'FileOptionsTextEditor.html';
 1123 : Result := 'FileOptionsMediaViewers.html';
 1124 : Result := 'FileOptionsService.html';
 1125 : Result := 'FileOptionsSearchForUpdates.html';
 1126 : Result := 'FileOptionsWindowsGames.html';
 1127 : Result := 'FileOptionsZipPackers.html';
 1128 : Result := 'FileOptionsGamesListTranslations.html';
 1129 : Result := 'FileOptionsListInIconsMode.html';
 1130 : Result := 'FileOptionsMenubar.html';
 1131 : Result := 'FileOptionsUserInterpreters.html';
 1132 : Result := 'FileOptionsImageScaling.html';
 1133 : Result := 'FileOptionsOtherEmulators.html';
 1134 : Result := 'FileOptionsAutomaticConfiguration.html';
 1135 : Result := 'FileOptionsDOSBoxGeneral.html';
 1136 : Result := 'FileOptionsDataPrivacy.html';
 1137 : Result := 'FileOptionsResetProfiles.html';
 1501 : Result := 'ViewQuickStarter.html';
 1751 : Result := 'RunDOSBoxOutputTest.html';
 2001 : Result := 'ProfileWithWizard.html';
 2003 : Result := 'ProfileCopy.html';
 2004 : Result := 'ProfileUninstall.html';
 2005 : Result := 'ProfileMakeInstallerPackage.html';
 2006 : Result := 'ProfileMakeZipPackage.html';
 2007 : Result := 'ProfileViewDOSBoxConfFile.html';
 2008 : Result := 'ProfileViewScummVMIniFile.html';
 2009 : Result := 'ProfileOpenProgramFolder.html';
 2010 : Result := 'ProfileOpenDataFolder.html';
 2011 : Result := 'ProfileOpenFileInDataFolder.html';
 2012 : Result := 'ProfileInternetAddress.html';
 2013 : Result := 'ProfileMarkAsFavorite.html';
 2014 : Result := 'ProfileCreateShortCut.html';
 2015 : Result := 'ProfileSearchGame.html';
 2016 : Result := 'ProfileAddFromMedia.html';
 2017 : Result := 'ProfileCheating.html';
 2100 : Result := 'ProfileEdit.html';
 2101 : Result := 'ProfileEditProfile.html';
 2102 : Result := 'ProfileEditProgramInformation.html';
 2103 : Result := 'ProfileEditProgramDirectories.html';
 2104 : Result := 'ProfileEditDOSBox.html';
 2105 : Result := 'ProfileEditScummVM.html';
 2106 : Result := 'ProfileEditScummVMGame.html';
 2107 : Result := 'ProfileEditCPU.html';
 2108 : Result := 'ProfileEditMemory.html';
 2109 : Result := 'ProfileEditGraphics.html';
 2110 : Result := 'ProfileEditKeyboard.html';
 2111 : Result := 'ProfileEditMouse.html';
 2112 : Result := 'ProfileEditSound.html';
 2113 : Result := 'ProfileEditSoundVolume.html';
 2114 : Result := 'ProfileEditSoundSoundBlaster.html';
 2115 : Result := 'ProfileEditSoundGUS.html';
 2116 : Result := 'ProfileEditSoundMIDI.html';
 2117 : Result := 'ProfileEditJoystick.html';
 2118 : Result := 'ProfileEditDrives.html';
 2119 : Result := 'ProfileEditSerialPorts.html';
 2120 : Result := 'ProfileEditNetwork.html';
 2121 : Result := 'ProfileEditPrinter.html';
 2122 : Result := 'ProfileEditDOSEnvironment.html';
 2123 : Result := 'ProfileEditStarting.html';
 2124 : Result := 'ProfileEditHelperPrograms.html';
 2125 : Result := 'ProfileEditHardware.html';
 2126 : Result := 'ProfileEditAdditionalChecksums.html';
 2127 : Result := 'ProfileEditSoundInnova.html';
 3001 : Result := 'ExtrasManageIcons.html';
 3002 : Result := 'ExtrasViewHistory.html';
 3003 : Result := 'ExtrasOpenGamesFolder.html';
 3004 : Result := 'ExtrasTemplates.html';
 3005 : Result := 'ExtrasImagesCreateImageFromFloppy.html';
 3006 : Result := 'ExtrasImagesWriteImageToFloppy.html';
 3007 : Result := 'ExtrasImagesCreateImage.html';
 3008 : Result := 'ExtrasImagesCreateImageFromCD.html';
 3009 : Result := 'ExtrasImagesExtractToFolder.html';
 3010 : Result := 'ExtrasImagesCreateFromFolder.html';
 3011 : Result := 'ExtrasScanGamesFolder.html';
 3012 : Result := 'ExtrasEditMultipleProfiles.html';
 3013 : Result := 'ExtrasUninstallMultipleGames.html';
 3014 : Result := 'ExtrasTransferProfiles.html';
 3017 : Result := 'ExtrasCheckProfiles.html';
 3018 : Result := 'ExtrasCreateShortcuts.html';
 3019 : Result := 'ExtrasLanguageEditor.html';
 3020 : Result := 'ExtrasImagesCreateFromProfile.html';
 3021 : Result := 'ExtrasEditCheatDB.html';
 3022 : Result := 'ExtrasSearchAddress.html';
 3023 : Result := 'ExtrasLanguageEditorDOSBox.html';
 4003 : Result := 'HelpStatistics.html';
 4004 : Result := 'HelpOperationMode.html';
 4006 : Result := 'HelpOldGames.html';
 4007 : Result := 'HelpGetGames.html';
  end;
end;

end.
